### PR TITLE
Allow Minitest > 5.5

### PR DESCRIPTION
**Pull request by kstevens715**

### CODE REVIEW

**Comment by jonesdeini** [comment]
want me to check this out? any specific things to poke?

**Comment by kstevens715** [comment]
It should just work. Just trying to remove the arbitrary requirement of a specific max version of Minitest. This adds a build to Travis to test with Minitest 5.6.1, so I think if Travis passes it should be good.

**Comment by kstevens715** [comment]
Using it in my personal project, Rubyles and I couldn't bundle.

**Comment by jonesdeini** [comment]
Original Gemfile
```ruby
gem "minitest", "5.6.1"
gem "minitest-bang", "1.0.1"
```
output:
🐈 jonesdeini@scooty_puff_jr ~/minitest-bang-test$ bundle
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
You have requested:
  minitest = 5.6.1

The bundle currently has minitest locked at 5.6.0.

Updated Gemfile
```ruby
gem "minitest", "5.6.1"
gem "minitest-bang", git: "git@github.com:kstevens715/minitest-bang.git", branch: "feature/upgrade-minitest"
```
New output
🐈 jonesdeini@scooty_puff_jr ~/minitest-bang-test$ bundle
Fetching git@github.com:kstevens715/minitest-bang.git
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Using minitest 5.6.1 (was 5.6.0)
Using minitest-bang 1.0.2 (was 1.0.1) from git@github.com:kstevens715/minitest-bang.git (at feature/upgrade-minitest)
Using bundler 1.7.10
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.

**Comment by jonesdeini** [comment]
seems legit :+1:

**Pull request merged**
